#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xBE793007AD22DF7E (tsujan2000@gmail.com)
#
Name     : libsysstat
Version  : 0.4.3
Release  : 5
URL      : https://github.com/lxqt/libsysstat/releases/download/0.4.3/libsysstat-0.4.3.tar.xz
Source0  : https://github.com/lxqt/libsysstat/releases/download/0.4.3/libsysstat-0.4.3.tar.xz
Source1  : https://github.com/lxqt/libsysstat/releases/download/0.4.3/libsysstat-0.4.3.tar.xz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: libsysstat-data = %{version}-%{release}
Requires: libsysstat-lib = %{version}-%{release}
Requires: libsysstat-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-qmake
BuildRequires : liblxqt-data
BuildRequires : lxqt-build-tools
BuildRequires : qtbase-dev

%description
# libsysstat
## Overview
libsysstat is a library to query system information like CPU and memory usage or
network traffic. Conceptually it's roughly similar to
[libstatgrab](https://www.i-scream.org/libstatgrab), a third-party library used
by LXQt as well.

%package data
Summary: data components for the libsysstat package.
Group: Data

%description data
data components for the libsysstat package.


%package dev
Summary: dev components for the libsysstat package.
Group: Development
Requires: libsysstat-lib = %{version}-%{release}
Requires: libsysstat-data = %{version}-%{release}
Provides: libsysstat-devel = %{version}-%{release}
Requires: libsysstat = %{version}-%{release}

%description dev
dev components for the libsysstat package.


%package lib
Summary: lib components for the libsysstat package.
Group: Libraries
Requires: libsysstat-data = %{version}-%{release}
Requires: libsysstat-license = %{version}-%{release}

%description lib
lib components for the libsysstat package.


%package license
Summary: license components for the libsysstat package.
Group: Default

%description license
license components for the libsysstat package.


%prep
%setup -q -n libsysstat-0.4.3
cd %{_builddir}/libsysstat-0.4.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1598905455
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1598905455
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libsysstat
cp %{_builddir}/libsysstat-0.4.3/COPYING %{buildroot}/usr/share/package-licenses/libsysstat/7fab4cd4eb7f499d60fe183607f046484acd6e2d
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/cmake/*

%files dev
%defattr(-,root,root,-)
/usr/include/sysstat-qt5/SysStat/BaseStat
/usr/include/sysstat-qt5/SysStat/CpuStat
/usr/include/sysstat-qt5/SysStat/Global
/usr/include/sysstat-qt5/SysStat/MemStat
/usr/include/sysstat-qt5/SysStat/NetStat
/usr/include/sysstat-qt5/SysStat/Version
/usr/include/sysstat-qt5/basestat.h
/usr/include/sysstat-qt5/cpustat.h
/usr/include/sysstat-qt5/memstat.h
/usr/include/sysstat-qt5/netstat.h
/usr/include/sysstat-qt5/sysstat_global.h
/usr/include/sysstat-qt5/version.h
/usr/lib64/libsysstat-qt5.so
/usr/lib64/pkgconfig/sysstat-qt5.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libsysstat-qt5.so.0
/usr/lib64/libsysstat-qt5.so.0.4.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libsysstat/7fab4cd4eb7f499d60fe183607f046484acd6e2d
